- hosts: sta-server
  become: yes
  pre_tasks:
    - name: "Installing gnupg"
      yum:
        name: gnupg
        state: present
        update_cache: no
  roles:
    - role: geerlingguy.nginx
    - role: oefenweb.r
    - role: oefenweb.shiny-server