- hosts: sta
  connection: local
  become: yes
  become_user: root
  vars:
    ansible_processor_vcpus: auto
    r_packages:
      - name : shiny
    shiny_server_version: 1.5.6.875
  roles:
    - role: geerlingguy.nginx
    - role: oefenweb.r
    - role: oefenweb.shiny-server
  tasks:
    - name: Clone github repository
      git:
        repo: https://github.com/abims-sbr/shiny_transcriptomic_aggregator_ectocarpus.git
        dest: /srv/shiny-server/shiny_transcriptomic_aggregator_ectocarpus/
        version: master