- name: Clone github repository
  ansible.builtin.git:
    repo: "{{ repo_name }}"
    dest: "{{ repo_folder }}"
    version: "{{ repo_version }}"
    accept_hostkey: yes
    force: yes
    recursive: no
- name: Copy shiny-sta nginx configuration file
  copy:
    src: "{{ shiny_conf }}"
    dest: "/etc/nginx/conf.d/{{ shiny_conf }}"
    owner: root
    group: root
    mode: '0644'
- name: Copy ldap-auth nginx configuration file
  copy:
    src: "{{ ldap_conf }}"
    dest: "/etc/nginx/conf.d/{{ ldap_conf }}"
    owner: root
    group: root
    mode: '0644'
